# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0fbac0a337ed173175d58f3fe725ac7bf2cad3501e9e6a5d3cf2d63eabb1773a3787b2afd1395f0cb1d5bb17a24849609a5b3d68d148508877b44e77ec70565

test:
  secret_key_base: 3dfeb1bed311bf59188c81ff61a67da732ef626ca4c1a95f1a733c3461446a5021e9dfa253439c861237ecbee95873dc227aa593f306becdc061b30c40ae9558

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
